### ISSUE TITLE
Powershell without Powershell Filters

### ISSUE THREAD

**Issue by ion-storm** [SwiftOnSecurity/sysmon-config#12]
I'd add logging of csc.exe and InstallUtil.exe to log compiling of executables and add logging of InstallUtil.exe since it can be used to execute powershell commands without invoking powershell.exe

**Comment by SwiftOnSecurity** [comment]
Are you talking about the networkconnect?

**Comment by ion-storm** [comment]
disregard, we already have this feature, just tested and detected.
