### ISSUE TITLE
TargetObect "HKLM\..." with condition"end with"

### ISSUE THREAD

**Issue by ManfMert** [SwiftOnSecurity/sysmon-config#21]
There are some TargetObjects like HKLM\SYSTEM\... with condition="end with". Is this correct?

<TargetObject condition="end with">HKLM\SYSTEM\CurrentControlSet\Control\Lsa\Audit</TargetObject>  
			<TargetObject condition="end with">HKLM\SYSTEM\CurrentControlSet\Control\Lsa\Audit\AuditPolicy</TargetObject>  
			<TargetObject condition="end with">HKLM\SYSTEM\CurrentControlSet\Control\Lsa\Audit\PerUserAuditing\System</TargetObject>  

Shouldn´t it be "begin with"?

**Comment by SwiftOnSecurity** [comment]
Hello,
This is done based on the theory that with pattern matching, it's easier to filter text strings based on the most unique attributes. Obviously, tons of registry changes start with HKLM\SYSTEM\CurrentControlSet, so you're wasting CPU having it match that.

However, if you start at the end, very few registry keys end with T, then I, the D, then U, then A, so unmatching keys are discarded earlier in the text matching process.

It's a very tiny performance optimization. I hope that makes sense!
