### ISSUE TITLE
Sysmon Event ID 7 : DLL (IMAGE) LOADED BY PROCESS not filtering

### ISSUE THREAD

**Issue by jrwalzer** [SwiftOnSecurity/sysmon-config#24]
I modified the sysmon config to filter out some Event ID 7 processes and when I load the config, I still see Event ID 7 processes in event viewer.  Anyone else having this issue?

	
		
		<ImageLoad onmatch="exclude">
			<Image condition="image">Conhost.exe</Image>
			<Image condition="image">whosip.exe</Image>
			<Image condition="image">g2mupdate.exe</Image>
			<Image condition="image">GoogleUpdate.exe</Image>
			<Image condition="image">FlashPlayerUpdateService.exe</Image>
			<Image condition="image">mscorsvw.exe </Image>
		
			<Image condition="image">splunkd.exe</Image>
			<Image condition="image">splunk-MonitorNoHandle.exe</Image>
			<Image condition="image">splunk-regmon.exe</Image>
			<Image condition="image">splunk-netmon.exe</Image>
			<Image condition="image">splunk-powershell.exe</Image>
			<Image condition="image">splunk-winprintmon.exe</Image>
			<Image condition="image">splunk-admon.exe</Image>
		</ImageLoad>

**Comment by dstaulcu** [comment]
your splunk related conditions worked for me as include rules with sysmon v6.0.  that would seem to validate the syntax.  I'll try the conditions as exclude later tonight when I have a more effective event message scanning harness to deal with the noise.

**Comment by jrwalzer** [comment]
Thx for testing as this is driving me crazy. Looking forward to what you discover.

**Comment by dstaulcu** [comment]
Looks like I can reproduce the problem too using sysmon v6.  I tried using the "is" condition with full path to image as well and but that also does not seem to work in an "exclude" filter strategy.

**Comment by jrwalzer** [comment]
Thx - I left a message in the Sysinternals Forum that this is a bug so hopefully it'll get fixed soon.

**Comment by jrwalzer** [comment]
All, the new version of Sysmon fixes this issue (https://technet.microsoft.com/en-us/sysinternals/sysmon)

**Comment by SwiftOnSecurity** [comment]
See @jrwalzer comment
