### ISSUE TITLE
Error with Sysmon v6.20 DTD prohibited

### ISSUE THREAD

**Issue by binarypathways** [SwiftOnSecurity/sysmon-config#43]
Sysmon v6.20 installed, Line 6 column 11 DTD prohibited error after command

sysmon.exe -c sysmonconfig-export.xml

**Comment by ottoscav** [comment]
Any fix for this?

**Comment by alexdatsko** [comment]
Couldn't get this to work on W10 x64.  Sysmon v7.01.  Got past the inital DTD error by getting rid of the DOCTYPE tag at the top.

Then I got this error:
Error: Incorrect XML configuration: sysmonconfig-export.xml
At line 34, column 88: A name contained an invalid character.

Line 34 has <link rel="sudo-modal" href="/sessions/sudo_modal">.  It's not close to 88 characters.  None of the lines around that line seem to have anything weird.  Not sure what to do about it.

**Comment by alexdatsko** [comment]
Oops, didn't escape the link tag.   Line 34 has <  link rel="sudo-modal" href="/sessions/sudo_modal"  >

**Comment by samitbrc** [comment]
Error: Incorrect XML configuration: sysmonconfig-export.xml
At line 41, column 89: A name contained an invalid character.
Any solution?

**Comment by weichea** [comment]
Same error as well, on sysmon v7.0.1

Error: Incorrect XML configuration: c:\Users\xxx\sysmonconfig-export.xml

At line 6, column 11: DTD is prohibited.

**Comment by ChrisM65** [comment]
Running version 7.01. Noticed I had to copy the file out instead of right clicking and choosing Save As. By copying just the text and using version 7.01, no error with xml.

**Comment by mike-nolan-councilman** [comment]
Yep same error for me and copying the XML text rather than saving the file fixed the issue.

**Comment by Cl0udAwl** [comment]
Hello, I'm having the same issue. Using Sysmon V9.0 on Win7 
Incorrect XML configuration: c:\StartLogging.xml
The system cannot locate the object specified.

**Comment by SwiftOnSecurity** [comment]
Please save the file using Google Chrome or with Git. Saving the file with Internet Explorer may cause issues.
