### ISSUE TITLE
Dropbox Updater

### ISSUE THREAD

**Issue by Darkbat91** [SwiftOnSecurity/sysmon-config#5]
Is the Dropbox updater considered sufficiently hardened? If so i think it would be prudent to add one of the below.

Image
C:\Program Files (x86)\Dropbox\Update\DropboxUpdate.exe 

Or Command line
"C:\Program Files (x86)\Dropbox\Update\DropboxUpdate.exe" /ua /installsource scheduler

**Comment by SwiftOnSecurity** [comment]
Right now I'm considering how deep I want to go into whitelisting with this, I could very well accept this request. Give me some time to mull it over. Appreciate your contributions! I'm so honored! @Darkbat91

**Comment by Darkbat91** [comment]
Understood, It is a complicated balance between whitelisting it so that there is not an over abundance of information and Making sure that information is not being Ignored which is important.

**Comment by SwiftOnSecurity** [comment]
Added in
