### ISSUE TITLE
having Zone identifier appended to the file name

### ISSUE THREAD

**Issue by anelshaer** [SwiftOnSecurity/sysmon-config#51]
Log Id 15 is generated like below, how can we get the file name after being created.
C:\Users\user1\Downloads\PortMon.zip.8g8if7a.partial:Zone.Identifier
C:\Users\user1\Downloads\PortMon.zip.8g8if7a.partial

i have two logs with the above file names after downloading the zip file with different hashes.
how can we get only the file name with the final hash after finishing download.

**Comment by SwiftOnSecurity** [comment]
I will contact Mark about this I've seen it too.
