### ISSUE TITLE
Possible Config Issue on Win10

### ISSUE THREAD

**Issue by robsmallridge** [SwiftOnSecurity/sysmon-config#56]
I have been able to install Sysmon (7.01) on my Windows 8.1 host and the latest config (f24dc22) with no issues.

However, using the same installation files and process, when installing on Windows 10, the installation fails to start the service (Service times out), when I specify the config with the initial install 
e.g. `sysmon.exe -accepteula -i sysmonconfig-export.xml`

Instead, I have to do 

`sysmon.exe -accepteula -i `
`sysmon.exe -c sysmonconfig-export.xml. `

When I update the config with the second command, this crashes the service and restarting also times out, so I can only assume there is an issue with the config on Win10, or my build. Has anyone seen this issue before? Have not been able to test on another Win10 build yet.

**Comment by tacom6** [comment]
I just experienced something along these lines where the installation was corrupted. Tried on a home W10 PC and it works fine. At work i tried 9.0, home 9.1. Reviewing further.

**Comment by SwiftOnSecurity** [comment]
Please use 

sysmon.exe -u force
