### ISSUE TITLE
Others minifilters - some logs are not saved by Sysmon

### ISSUE THREAD

**Issue by kont45** [SwiftOnSecurity/sysmon-config#57]
It's a very interesting things on 445 line:
https://github.com/SwiftOnSecurity/sysmon-config/blob/master/sysmonconfig-export.xml  
```
<!--SYSMON EVENT ID 11 : FILE CREATED [FileCreate]-->
		<!--EVENT 11: "File created"-->
		<!--NOTE:	Other filesystem "minifilters" can make it appear to Sysmon that some files are being written twice. This is not a Sysmon issue, per Mark Russinovich.-->
<!--NOTE:	You may not see files detected by antivirus. Other filesystem minifilters, like antivirus, can act before Sysmon receives the alert a file was written.-->
```

Could someone explain me in datails why sysmon or Windows Event doesn't save some logs for file create event, if for example a antivirus has detect and deleted malware? 

Is any way to make a higher priority for sysmon / windows event to capture all events before others minifilters like as antivirus? Or is exist another tools to do this?

**Comment by SwiftOnSecurity** [comment]
Unfortunately those are not things Sysmon is designed to monitor. I'm sorry I do not write the tool I only provide configurations. @MarkRussinovich is on Twitter for feedback.
