### ISSUE TITLE
Sysmon Event ID 10 "Process accessed" not filtering

### ISSUE THREAD

**Issue by rmfatemi** [SwiftOnSecurity/sysmon-config#61]
So I edited the configuration to include watching for events generated by `LSASS.exe` and also removed `VBoxService.exe` to make the logs less noisy.

I added the following lines. 

```
<ProcessAccess onmatch="include">
    <TargetImage condition="is">C:\Windows\system32\lsass.exe</TargetImage>
</ProcessAccess>
<!-- Processes that you wish to exclude -->
<ProcessAccess onmatch="exclude">
    <SourceImage condition="is">C:\WINDOWS\System32\VBoxService.exe</SourceImage>
</ProcessAccess>
```

But I still see the logs with the source image `VBoxService.exe` and target image `lsass.exe`. Anyone else having a similar issue?

**Comment by coleJ98** [comment]
Hi @rmfatemi,

Did you manage to fix this issue? I am seeing similar problems. I wanted to filter out a whole event ID (event id 2) because its noisy. However I cannot do so even though my config file does not have this event id defined.

Please let me know how you manged to get around this problem, Thanks!

**Comment by cyberkryption** [comment]
Gentlemen,

Can i suggest you check the format of you of your exclusion, the path is in
the incorrect place.

Cyberkryption

**Comment by rmfatemi** [comment]
@coleJ98 Hi, Sysmon has been updated quite a few times after I posted this. As far as I remember, the issue was resolved after a Sysmon update. I still use it the same way and it's working just fine.

@cyberkryption I checked the path a few times and it was correct. I copied the path from the log itself so it should be the right path. But thanks for the suggestion.
