### ISSUE TITLE
Typo with rtf

### ISSUE THREAD

**Issue by polylogyx** [SwiftOnSecurity/sysmon-config#64]
In the FilleEvent "include" filters, it says 

".rft"[--RTF files often 0day malware vectors when opened by Office-]

It should be ".rtf"

**Comment by robertstrom** [comment]
I just saw this one myself ... you beat me to it.

<TargetFilename condition="end with">.rft</TargetFilename>

**Comment by SwiftOnSecurity** [comment]
Got this fixed thanks
