### ISSUE TITLE
Incorrect Registry Location for WDigest Vuln

### ISSUE THREAD

**Issue by twingbat** [SwiftOnSecurity/sysmon-config#67]
Thanks for the great config!

While testing, we noticed there is a misconfig related to the WDigest registry on line 619.
The registry is listed as:
HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SecurityProviders
But that has too many "SecurityProviders" and the actual entry should be:
HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders

We've tested it and this change works for the WDigest registry detection. Per https://blogs.technet.microsoft.com/kfalde/2014/11/01/kb2871997-and-wdigest-part-1/ :

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest

**Comment by SwiftOnSecurity** [comment]
I got this fixed in the past, I don't remember when. Thank you.
