### ISSUE TITLE
Wmi Events Log Generation

### ISSUE THREAD

**Issue by nterl0k** [SwiftOnSecurity/sysmon-config#68]
The current config doesn't produce any WMI events out of the box. 

Should the WmiEvent section of the config be set to "exclude" instead of "include" ?

IE below:

WmiEvent onmatch="exclude"

/WmiEvent

**Comment by SwiftOnSecurity** [comment]
After Sysmon was enhanced to make this more useful, this setting is being changed in the next version. Thank you.
