### ISSUE TITLE
sysmonconfig-export.xml - Possible error in IMAP port

### ISSUE THREAD

**Issue by fabamatic** [SwiftOnSecurity/sysmon-config#73]
I may be wrong but looks like there is an small error in sysmonconfig-export.xml, 142 is listed as IMAP mail protocol port but to IANA's Service Name and Transport Protocol Port Number Registry 143 seems to be the correct one (https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=IMAP)

**Comment by SwiftOnSecurity** [comment]
Great catch! This will be fixed in the next version.
