### ISSUE TITLE
Monitor network traffic to dynamic DNS domains

### ISSUE THREAD

**Issue by daniel-gallagher** [SwiftOnSecurity/sysmon-config#9]
I believe that events for traffic going to dynamic DNS providers can be a solid indicator of suspicious activity, at least in an enterprise environment. I have added a few of the domains that I see most frequently used by malware.

[https://github.com/daniel-gallagher/sysmon-config/commit/d26898eff4b69a9c1ca6aea66f39140eb9838139#diff-42b0eea836e3eeb205ac37691ac81168L103](https://github.com/daniel-gallagher/sysmon-config/commit/d26898eff4b69a9c1ca6aea66f39140eb9838139#diff-42b0eea836e3eeb205ac37691ac81168L103)

**Comment by SwiftOnSecurity** [comment]
Hi Daniel,
That's a great idea! Unfortunately that link is broken, can you re-send?

**Comment by daniel-gallagher** [comment]
Not enough coffee so far this morning... :) I edited the URL, so it should work now.
